"""add PlayerIdentity table

Revision ID: 61d82684c3db
Revises: 836b926e7463
Create Date: 2026-07-31 14:06:48.358762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61d82684c3db'
down_revision: Union[str, Sequence[str], None] = '836b926e7463'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_identities',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('provider_user_id', sa.String(), nullable=False),
    sa.Column('player_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_user_id', name='uq_identity_provider_user')
    )
    op.create_index('ix_identity_provider_user', 'player_identities', ['provider', 'provider_user_id'], unique=False)
    op.create_index(op.f('ix_player_identities_player_id'), 'player_identities', ['player_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_player_identities_player_id'), table_name='player_identities')
    op.drop_index('ix_identity_provider_user', table_name='player_identities')
    op.drop_table('player_identities')
    # ### end Alembic commands ###
